"""initial hospital management system schema

Revision ID: 122a879fc495
Revises: 
Create Date: 2026-08-27 11:40:25.238314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '122a879fc495'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.CheckConstraint('length(trim(address)) > 0', name='ck_hospitals_address_not_empty'),
    sa.CheckConstraint('length(trim(name)) > 0', name='ck_hospitals_name_not_empty'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospitals_email'), 'hospitals', ['email'], unique=True)
    op.create_index('ix_hospitals_name', 'hospitals', ['name'], unique=False)
    op.create_table('medicines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('length(trim(name)) > 0', name='ck_medicines_name_not_empty'),
    sa.CheckConstraint('unit_price >= 0', name='ck_medicines_unit_price_nonnegative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_medicines_name', 'medicines', ['name'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.CheckConstraint('length(trim(name)) > 0', name='ck_patients_name_not_empty'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_email'), 'patients', ['email'], unique=False)
    op.create_index('ix_patients_phone', 'patients', ['phone'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.CheckConstraint('length(trim(name)) > 0', name='ck_roles_name_not_empty'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_roles_name', 'roles', ['name'], unique=False)
    op.create_table('test_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('length(trim(name)) > 0', name='ck_test_types_name_not_empty'),
    sa.CheckConstraint('price >= 0', name='ck_test_types_price_nonnegative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('length(trim(name)) > 0', name='ck_departments_name_not_empty'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id', 'name', name='uq_departments_hospital_name')
    )
    op.create_index('ix_departments_hospital_id', 'departments', ['hospital_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('invoice_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.CheckConstraint("status IN ('unpaid', 'partially_paid', 'paid', 'cancelled')", name='ck_invoices_status'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invoices_invoice_date', 'invoices', ['invoice_date'], unique=False)
    op.create_index('ix_invoices_patient_id', 'invoices', ['patient_id'], unique=False)
    op.create_index('ix_invoices_status', 'invoices', ['status'], unique=False)
    op.create_table('medicine_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('unit_cost >= 0', name='ck_medicine_batches_unit_cost_nonnegative'),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medicine_id', 'batch_number', name='uq_medicine_batches_medicine_batch')
    )
    op.create_index('ix_medicine_batches_expiry_date', 'medicine_batches', ['expiry_date'], unique=False)
    op.create_index('ix_medicine_batches_medicine_id', 'medicine_batches', ['medicine_id'], unique=False)
    op.create_table('pharmacies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('length(trim(name)) > 0', name='ck_pharmacies_name_not_empty'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id', 'name', name='uq_pharmacies_hospital_name')
    )
    op.create_index('ix_pharmacies_hospital_id', 'pharmacies', ['hospital_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(trim(name)) > 0', name='ck_users_name_not_empty'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_role_id', 'users', ['role_id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('employment_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("employment_status IN ('active', 'inactive', 'on_leave', 'terminated')", name='ck_employees_status'),
    sa.CheckConstraint('length(trim(name)) > 0', name='ck_employees_name_not_empty'),
    sa.CheckConstraint('salary IS NULL OR salary >= 0', name='ck_employees_salary_nonnegative'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_employees_department_id', 'employees', ['department_id'], unique=False)
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_index('ix_employees_role_id', 'employees', ['role_id'], unique=False)
    op.create_table('invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_invoice_items_amount_nonnegative'),
    sa.CheckConstraint('quantity > 0', name='ck_invoice_items_quantity_positive'),
    sa.CheckConstraint('unit_price >= 0', name='ck_invoice_items_unit_price_nonnegative'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invoice_items_invoice_id', 'invoice_items', ['invoice_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('transaction_reference', sa.String(length=100), nullable=True),
    sa.CheckConstraint("payment_method IN ('cash', 'card', 'upi', 'bank_transfer', 'other')", name='ck_payments_method'),
    sa.CheckConstraint("status IN ('pending', 'completed', 'failed', 'refunded')", name='ck_payments_status'),
    sa.CheckConstraint('amount > 0', name='ck_payments_amount_positive'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_reference')
    )
    op.create_index('ix_payments_invoice_id', 'payments', ['invoice_id'], unique=False)
    op.create_index('ix_payments_payment_date', 'payments', ['payment_date'], unique=False)
    op.create_table('pharmacy_stock',
    sa.Column('pharmacy_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='ck_pharmacy_stock_quantity_nonnegative'),
    sa.ForeignKeyConstraint(['batch_id'], ['medicine_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pharmacy_id', 'batch_id')
    )
    op.create_index('ix_pharmacy_stock_batch_id', 'pharmacy_stock', ['batch_id'], unique=False)
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_number', sa.String(length=20), nullable=False),
    sa.Column('room_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('available', 'occupied', 'maintenance', 'inactive')", name='ck_rooms_status'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id', 'room_number', name='uq_rooms_hospital_room_number')
    )
    op.create_index('ix_rooms_department_id', 'rooms', ['department_id'], unique=False)
    op.create_index('ix_rooms_hospital_id', 'rooms', ['hospital_id'], unique=False)
    op.create_table('beds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bed_number', sa.String(length=20), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.CheckConstraint("status IN ('available', 'occupied', 'maintenance', 'inactive')", name='ck_beds_status'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'bed_number', name='uq_beds_room_bed_number')
    )
    op.create_index('ix_beds_room_id', 'beds', ['room_id'], unique=False)
    op.create_table('doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('specialization', sa.String(length=100), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.CheckConstraint('experience_years IS NULL OR experience_years >= 0', name='ck_doctors_experience_nonnegative'),
    sa.CheckConstraint('length(trim(specialization)) > 0', name='ck_doctors_specialization_not_empty'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_index('ix_doctors_employee_id', 'doctors', ['employee_id'], unique=False)
    op.create_table('vitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('recorded_by', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('heart_rate', sa.Integer(), nullable=True),
    sa.Column('blood_pressure_systolic', sa.Integer(), nullable=True),
    sa.Column('blood_pressure_diastolic', sa.Integer(), nullable=True),
    sa.Column('respiratory_rate', sa.Integer(), nullable=True),
    sa.Column('oxygen_saturation', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('weight', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.CheckConstraint('blood_pressure_diastolic IS NULL OR blood_pressure_diastolic > 0', name='ck_vitals_bp_diastolic_positive'),
    sa.CheckConstraint('blood_pressure_systolic IS NULL OR blood_pressure_systolic > 0', name='ck_vitals_bp_systolic_positive'),
    sa.CheckConstraint('heart_rate IS NULL OR heart_rate > 0', name='ck_vitals_heart_rate_positive'),
    sa.CheckConstraint('oxygen_saturation IS NULL OR (oxygen_saturation >= 0 AND oxygen_saturation <= 100)', name='ck_vitals_oxygen_saturation'),
    sa.CheckConstraint('respiratory_rate IS NULL OR respiratory_rate > 0', name='ck_vitals_respiratory_rate_positive'),
    sa.CheckConstraint('temperature IS NULL OR temperature > 0', name='ck_vitals_temperature_positive'),
    sa.CheckConstraint('weight IS NULL OR weight > 0', name='ck_vitals_weight_positive'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recorded_by'], ['employees.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vitals_patient_recorded_at', 'vitals', ['patient_id', 'recorded_at'], unique=False)
    op.create_index('ix_vitals_recorded_by', 'vitals', ['recorded_by'], unique=False)
    op.create_table('admissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('bed_id', sa.Integer(), nullable=False),
    sa.Column('admission_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('discharge_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.CheckConstraint("status IN ('admitted', 'discharged', 'cancelled')", name='ck_admissions_status'),
    sa.CheckConstraint('discharge_date IS NULL OR discharge_date >= admission_date', name='ck_admissions_discharge_date'),
    sa.ForeignKeyConstraint(['bed_id'], ['beds.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_admissions_bed_id', 'admissions', ['bed_id'], unique=False)
    op.create_index('ix_admissions_doctor_id', 'admissions', ['doctor_id'], unique=False)
    op.create_index('ix_admissions_patient_id', 'admissions', ['patient_id'], unique=False)
    op.create_index('ix_admissions_status', 'admissions', ['status'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('appointment_time', sa.Time(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.CheckConstraint("status IN ('scheduled', 'completed', 'cancelled', 'no_show')", name='ck_appointments_status'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_id', 'appointment_date', 'appointment_time', name='uq_appointments_doctor_datetime')
    )
    op.create_index('ix_appointments_doctor_date', 'appointments', ['doctor_id', 'appointment_date'], unique=False)
    op.create_index('ix_appointments_patient_id', 'appointments', ['patient_id'], unique=False)
    op.create_table('doctor_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(length=10), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.CheckConstraint("day_of_week IN ('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday')", name='ck_doctor_schedules_day'),
    sa.CheckConstraint('end_time > start_time', name='ck_doctor_schedules_time'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_doctor_schedules_doctor_id', 'doctor_schedules', ['doctor_id'], unique=False)
    op.create_table('lab_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_type_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('technician_id', sa.Integer(), nullable=False),
    sa.Column('test_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'in_progress', 'completed', 'cancelled')", name='ck_lab_tests_status'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['technician_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['test_type_id'], ['test_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lab_tests_doctor_id', 'lab_tests', ['doctor_id'], unique=False)
    op.create_index('ix_lab_tests_patient_id', 'lab_tests', ['patient_id'], unique=False)
    op.create_index('ix_lab_tests_technician_id', 'lab_tests', ['technician_id'], unique=False)
    op.create_index('ix_lab_tests_test_date', 'lab_tests', ['test_date'], unique=False)
    op.create_index('ix_lab_tests_test_type_id', 'lab_tests', ['test_type_id'], unique=False)
    op.create_table('medical_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('diagnosis', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('record_date', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(trim(diagnosis)) > 0', name='ck_medical_records_diagnosis_not_empty'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_medical_records_doctor_id', 'medical_records', ['doctor_id'], unique=False)
    op.create_index('ix_medical_records_patient_id', 'medical_records', ['patient_id'], unique=False)
    op.create_index('ix_medical_records_record_date', 'medical_records', ['record_date'], unique=False)
    op.create_table('prescriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('pharmacy_id', sa.Integer(), nullable=True),
    sa.Column('prescription_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prescriptions_date', 'prescriptions', ['prescription_date'], unique=False)
    op.create_index('ix_prescriptions_doctor_id', 'prescriptions', ['doctor_id'], unique=False)
    op.create_index('ix_prescriptions_patient_id', 'prescriptions', ['patient_id'], unique=False)
    op.create_index('ix_prescriptions_pharmacy_id', 'prescriptions', ['pharmacy_id'], unique=False)
    op.create_table('lab_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lab_test_id', sa.Integer(), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('reference_range', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(trim(result)) > 0', name='ck_lab_results_result_not_empty'),
    sa.ForeignKeyConstraint(['lab_test_id'], ['lab_tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lab_test_id')
    )
    op.create_table('nurse_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admission_id', sa.Integer(), nullable=False),
    sa.Column('nurse_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unassigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('unassigned_at IS NULL OR unassigned_at >= assigned_at', name='ck_nurse_assignments_dates'),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['nurse_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_nurse_assignments_admission_id', 'nurse_assignments', ['admission_id'], unique=False)
    op.create_index('ix_nurse_assignments_nurse_id', 'nurse_assignments', ['nurse_id'], unique=False)
    op.create_table('prescription_medicines',
    sa.Column('prescription_id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=False),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('instructions', sa.String(length=255), nullable=True),
    sa.CheckConstraint('length(trim(dosage)) > 0', name='ck_prescription_medicines_dosage_not_empty'),
    sa.CheckConstraint('quantity > 0', name='ck_prescription_medicines_quantity_positive'),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prescription_id', 'medicine_id')
    )
    op.create_index('ix_prescription_medicines_medicine_id', 'prescription_medicines', ['medicine_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prescription_medicines_medicine_id', table_name='prescription_medicines')
    op.drop_table('prescription_medicines')
    op.drop_index('ix_nurse_assignments_nurse_id', table_name='nurse_assignments')
    op.drop_index('ix_nurse_assignments_admission_id', table_name='nurse_assignments')
    op.drop_table('nurse_assignments')
    op.drop_table('lab_results')
    op.drop_index('ix_prescriptions_pharmacy_id', table_name='prescriptions')
    op.drop_index('ix_prescriptions_patient_id', table_name='prescriptions')
    op.drop_index('ix_prescriptions_doctor_id', table_name='prescriptions')
    op.drop_index('ix_prescriptions_date', table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index('ix_medical_records_record_date', table_name='medical_records')
    op.drop_index('ix_medical_records_patient_id', table_name='medical_records')
    op.drop_index('ix_medical_records_doctor_id', table_name='medical_records')
    op.drop_table('medical_records')
    op.drop_index('ix_lab_tests_test_type_id', table_name='lab_tests')
    op.drop_index('ix_lab_tests_test_date', table_name='lab_tests')
    op.drop_index('ix_lab_tests_technician_id', table_name='lab_tests')
    op.drop_index('ix_lab_tests_patient_id', table_name='lab_tests')
    op.drop_index('ix_lab_tests_doctor_id', table_name='lab_tests')
    op.drop_table('lab_tests')
    op.drop_index('ix_doctor_schedules_doctor_id', table_name='doctor_schedules')
    op.drop_table('doctor_schedules')
    op.drop_index('ix_appointments_patient_id', table_name='appointments')
    op.drop_index('ix_appointments_doctor_date', table_name='appointments')
    op.drop_table('appointments')
    op.drop_index('ix_admissions_status', table_name='admissions')
    op.drop_index('ix_admissions_patient_id', table_name='admissions')
    op.drop_index('ix_admissions_doctor_id', table_name='admissions')
    op.drop_index('ix_admissions_bed_id', table_name='admissions')
    op.drop_table('admissions')
    op.drop_index('ix_vitals_recorded_by', table_name='vitals')
    op.drop_index('ix_vitals_patient_recorded_at', table_name='vitals')
    op.drop_table('vitals')
    op.drop_index('ix_doctors_employee_id', table_name='doctors')
    op.drop_table('doctors')
    op.drop_index('ix_beds_room_id', table_name='beds')
    op.drop_table('beds')
    op.drop_index('ix_rooms_hospital_id', table_name='rooms')
    op.drop_index('ix_rooms_department_id', table_name='rooms')
    op.drop_table('rooms')
    op.drop_index('ix_pharmacy_stock_batch_id', table_name='pharmacy_stock')
    op.drop_table('pharmacy_stock')
    op.drop_index('ix_payments_payment_date', table_name='payments')
    op.drop_index('ix_payments_invoice_id', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_invoice_items_invoice_id', table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_index('ix_employees_role_id', table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_index('ix_employees_department_id', table_name='employees')
    op.drop_table('employees')
    op.drop_index('ix_users_role_id', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_pharmacies_hospital_id', table_name='pharmacies')
    op.drop_table('pharmacies')
    op.drop_index('ix_medicine_batches_medicine_id', table_name='medicine_batches')
    op.drop_index('ix_medicine_batches_expiry_date', table_name='medicine_batches')
    op.drop_table('medicine_batches')
    op.drop_index('ix_invoices_status', table_name='invoices')
    op.drop_index('ix_invoices_patient_id', table_name='invoices')
    op.drop_index('ix_invoices_invoice_date', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('ix_departments_hospital_id', table_name='departments')
    op.drop_table('departments')
    op.drop_table('test_types')
    op.drop_index('ix_roles_name', table_name='roles')
    op.drop_table('roles')
    op.drop_index('ix_patients_phone', table_name='patients')
    op.drop_index(op.f('ix_patients_email'), table_name='patients')
    op.drop_table('patients')
    op.drop_index('ix_medicines_name', table_name='medicines')
    op.drop_table('medicines')
    op.drop_index('ix_hospitals_name', table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_email'), table_name='hospitals')
    op.drop_table('hospitals')
    # ### end Alembic commands ###
