from .users import UserDB
from .hospital import HospitalDB
from .department import DepartmentDB
from .role import RoleDB
from .employee import EmployeeDB
from .doctor import DoctorDB
from .patient import PatientDB
from .appointments import AppointmentDB
from .doctorScedule import DoctorScheduleDB
from .medical_record import MedicalRecordDB
from .vitals import VitalDB
from .admission import AdmissionDB
from .room import RoomDB
from .bed import BedDB
from .nurse_assignment import NurseAssignmentDB
from .test import TestTypeDB
from .lab import LabTestDB
from .lab_result import LabResultDB
from .medicine import MedicineDB
from .medical_batch import MedicineBatchDB
from .pharmacy import PharmacyDB
from .pharmacy_Stock import PharmacyStockDB
from .prescription import PrescriptionDB
from .prescription_medicine import PrescriptionMedicineDB
from .invoice import InvoiceDB
from .invoice_item import InvoiceItemDB
from .payment import PaymentDB